const mongoose = require("mongoose");
const jwt = require("jsonwebtoken");
function mockRes() {
  const res = {};
  res.statusCode = 200;
  res.body = null;
  res.status = (c) => { res.statusCode = c; return res; };
  res.json = (b) => { res.body = b; return res; };
  return res;
}
module.exports = async () => {
  const g = global.__P25;
  const { admin, normal, other, media, adminCtl, reportCtl, authMw, mongod, results, record } = g;
  const Report = require("../../server/src/models/Report");
  const Media = require("../../server/src/models/Media");
  const User = require("../../server/src/models/User");
  const rC = mockRes();
  await reportCtl.createReport({ user: { id: normal._id }, body: { targetType: "media", targetId: String(media._id), reason: "spam" } }, rC);
  record("createReport valid -> 201", rC.statusCode === 201 && !!(rC.body && rC.body.report), rC.statusCode);
  const rB = mockRes();
  await reportCtl.createReport({ user: { id: normal._id }, body: { targetType: "media", targetId: String(other._id), reason: "x" } }, rB);
  record("createReport bad target -> 404", rB.statusCode === 404, rB.statusCode);
  const st = mockRes();
  await adminCtl.getStats({ user: { id: admin._id } }, st);
  const s = st.body && st.body.stats;
  record("stats real counts", !!(s && s.totalUsers === 3 && s.totalCreators === 1 && s.totalMedia === 1), JSON.stringify(s || {}));
  const rep = await Report.findOne().lean();
  const rl = mockRes();
  await adminCtl.listReports({ user: { id: admin._id }, query: {} }, rl);
  record("listReports paginated", !!(rl.body && Array.isArray(rl.body.reports) && rl.body.pagination), "ok");
  const rg = mockRes();
  await adminCtl.getReport({ params: { id: String(rep._id) } }, rg);
  record("getReport + safe target", !!(rg.body && rg.body.report && rg.body.target), "ok");
  const ru = mockRes();
  await adminCtl.updateReport({ user: { id: admin._id }, params: { id: String(rep._id) }, body: { status: "reviewing" } }, ru);
  record("updateReport reviewing", !!(ru.body && ru.body.report && ru.body.report.status === "reviewing"), "ok");
  const hid = mockRes();
  await adminCtl.hideMedia({ user: { id: admin._id }, params: { id: String(media._id) } }, hid);
  const ah = await Media.findById(media._id).lean();
  record("hideMedia reversible", !!(hid.body && hid.body.success && ah.isHidden === true), String(ah.isHidden));
  const rst = mockRes();
  await adminCtl.restoreMedia({ user: { id: admin._id }, params: { id: String(media._id) } }, rst);
  const ar = await Media.findById(media._id).lean();
  record("restoreMedia", !!(rst.body && rst.body.success && ar.isHidden === false), String(ar.isHidden));
  await Report.create({ reporter: normal._id, targetType: "user", targetId: other._id, reason: "abuse" });
  const w = mockRes();
  await adminCtl.warnUser({ user: { id: admin._id }, params: { id: String(other._id) }, body: { message: "Be nice" } }, w);
  record("warnUser notifies", !!(w.body && w.body.success), "ok");
  const su = mockRes();
  await adminCtl.suspendUser({ user: { id: String(admin._id) }, params: { id: String(other._id) }, body: { reason: "spam" } }, su);
  const susp = await User.findById(other._id).lean();
  record("suspendUser audit", !!(su.body && su.body.success && susp.isSuspended && susp.suspendedBy), String(susp.isSuspended));
  const stok = jwt.sign({ id: other._id, email: other.email }, process.env.JWT_SECRET);
  const srs = mockRes();
  await authMw({ headers: { authorization: "Bearer " + stok } }, srs, () => {});
  record("suspended auth -> 403", srs.statusCode === 403, srs.statusCode);
  const un = mockRes();
  await adminCtl.unsuspendUser({ user: { id: admin._id }, params: { id: String(other._id) } }, un);
  record("unsuspendUser", !!(un.body && un.body.success), "ok");
  record("publishing untouched", media.status === "published", media.status);
  await mongoose.disconnect();
  if (mongod) await mongod.stop();
  const failed = results.filter((r) => !r.pass);
  console.log("---- phase25: " + (results.length - failed.length) + "/" + results.length + " passed ----");
  process.exit(failed.length ? 1 : 0);
};
